name: PR preview - build image artifact

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          outputs: type=local,dest=./image-artifact
          platforms: linux/amd64,linux/arm64

      - name: Archive built image
        uses: actions/upload-artifact@v4
        with:
          name: image-artifact
          path: ./image-artifact
